config/routes.rb
Rails.application.routes.draw do

  get "/",                    to: "home#index",             as: :root

  get "/auth/rdio/callback",  to: "sessions#create",        as: :connect

  post "/album",              to: "home#album",             as: :album

  post "/lyrics",             to: "lyrics#index",           as: :lyrics

  get "/logout",              to: "sessions#destroy",       as: :destroy_session

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :uid, presence: :true
  validates :first_name, presence: :true

  def self.create_from_omniauth(auth_hash)
    User.create(
      uid:                  auth_hash["uid"].to_s,
      image:                auth_hash["info"]["image"],
      first_name:           auth_hash["info"]["first_name"],
      last_name:            auth_hash["info"]["last_name"],
      rdio_access_token:    auth_hash["credentials"]["token"],
      rdio_access_secret:   auth_hash["credentials"]["secret"]
    )
  end

  def self.find_or_create_from_omniauth(auth_hash)
    if user = User.find_by(uid: auth_hash["uid"].to_s)
        return user
    else
        User.create_from_omniauth(auth_hash)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def current_user
    if session[:user_id]
      @user = User.find_by(uid: session[:user_id])
    end
  end

  helper_method(:current_user)
end

app/controllers/home_controller.rb
require_dependency './lib/rdio'
require_dependency './lib/musixmatch'

class HomeController < ApplicationController
  def index
    if current_user
      @playlists = RdioSetter.new(current_user).get_playlists
      @key = @playlists["owned"][0]["key"]
    end
  end

  def album
    album = params[:album]
    @albumcolor = RdioSetter.new(current_user).get_color(album)
    respond_to do |format|
      format.json { render json: @albumcolor }
    end
  end
end

app/controllers/lyrics_controller.rb
require_dependency './lib/musixmatch'

class LyricsController < ApplicationController
  def index
    artist = params[:artist]
    track = params[:track]
    @subtitles_as_hash = MusixmatchSetter.subtitles_as_hash(track, artist)
    @seconds_and_lyrics = MusixmatchSetter.hash_to_time(@subtitles_as_hash)
    respond_to do |format|
      format.json { render json: @seconds_and_lyrics }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth_hash = request.env['omniauth.auth']
    session[:user_id] = User.find_or_create_from_omniauth(auth_hash).uid
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lyrics_helper.rb
module LyricsHelper
end

app/views/home/_about.html.erb
<div class='modal-header'>
 <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>x</button>
 <div class='modal-title'><h2><b><center>About Rdio Karaoke</center></b></h2></div>
</div>

<div class='modal-body'>
  <div>
    <p>This app was created by <a href="https://github.com/rmoshier"target="_blank">Rachel Adler</a> as her capstone project for the <a href="http://adadevelopersacademy.org" target="_blank">Ada Developers Academy</a>.</p>
  </div>
  <div>
    <p>To use this app, sign-in to Rdio using the link above, or sign-up for Rdio using the link below if you are not currently a member. Once you are signed in, create a playlist and then add the karaoke songs you want to the playlist.</p>
  </div>
  <div>
    <p>Rdio Karaoke is powered by <a href="http://rdio.com" target="_blank">Rdio</a> and <a href="http://musixmatch.com" target=_"blank">MusixMatch</a>.</p>
    <div id="photos">
      <%= (image_tag "rdio-logo.png", size: "1X10") %>
      <%= (image_tag "mm.jpg", size: "1X10") %>
    </div>
  </div>
  <div>
    <p>Thank you to all of my friends, TAs, and instructors at Ada who helped me with this app, as well as Varun from MusixMatch!</p>
  </div>
</div>

app/views/layouts/_guest.html.erb
<div class="row image" media="(max-width: 800px)">
    <%= (image_tag "scarlett.png", :id => "splash-picture")%>
    <h1 class="rdio-splash-1">Rdio</h1>
    <h1 class="rdio-splash-2">Karaoke</h1>
</div>

app/views/layouts/_signedin.html.erb
<div class="container-fluid">

  <div class="text-center">
    <h1><span id="lyrics"></span></h1>
  </div>

  <div class="box" id="apiswf"></div>

    <div class="row" class="container-fluid">

      <div class="col-md-6 col-md-offset-4 button-class" style="center">
        <div class="playControls btn-group">
          <button id="play" class="btn btn-default"><i class="fa fa-play-circle"></i> Play</button>
          <button id="stop" class="btn btn-default"><i class="fa fa-stop"></i> Stop</button>
          <button id="pause" class="btn btn-default"><i class="fa fa-pause"></i> Pause</button>
          <button id="previous" class="btn btn-default"><i class="fa fa-step-backward"></i> Previous</button>
          <button id="next" class="btn btn-default"><i class="fa fa-step-forward"></i> Next</button>
        </div>
      </div>

    </div>

    <div class="row" style="overflow: hidden;">
      <div style="margin-bottom: 10px;">
        <% if current_user %>
          <div>
            <input id="play_key" class="form-control" value="<%=@key%>" type="hidden">
          </div>
        <% end %>
      </div>
    </div>

    <div class="wtf" style="center">
      <h5>Artist: <span id="artist"></span></h5>
      <h5>Track: <span id="track"></span></h5>
      <h5>Album: <span id="album"></span></h5>
      <h5>Position: <span id="position"></span></h5>
    </div>

    <div class="wtf" style="overflow: hidden;">
      <div class="artistAlbumInfo"  style="center">
        <img src="" id="art" class="albumArt">
      </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag "rdio-app-icon.png"%>
    <title>Karaoke</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  </head>

  <body>

    <div id='event-modal-window' class='modal fade' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true' data-backdrop="false">
      <div class='modal-dialog'>
        <div class='modal-content'>
          <%= render 'home/about'%>
        </div>
      </div>
    </div>

    <div id="nav" class="container-fluid">
      <div class="row" style="margin: 10px;">
        <% if !current_user %>
          <%= link_to "Login with Rdio", "/auth/rdio" %>
          <%= (image_tag "rdio-app-icon.png", size: "20x20") %>
          <a id="fmly"  href='javascript:void(0)' onClick="$('#event-modal-window').modal()"> About </a>
        <% else %>
          <%= "Welcome to Rdio Karaoke!" %>
          <br>
          <%= current_user.first_name %>
          <img class="img-circle"<%= image_tag current_user.image %>
          <%= link_to "Logout", destroy_session_path %>
        <% end %>
      </div>
    </div>

    <% if current_user %>
      <%= render "layouts/signedin" %>
    <% else %>
      <%= render "layouts/guest" %>
    <% end %>

    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>

</html>